import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"ROOT LEGACY",
            artist: "ROOTLEGACY",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg
",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://rootslegacy.fr:8080/stream/1/",
            active: true,
        },
        {
            name:"Calm Radio",
            artist: "CalmRadio",
            cover: "https://img.freepik.com/psd-gratis/maqueta-microfono-escritorio-rectangular-vista-frontal_1332-10597.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://streams.calmradio.com:18928/stream/1/",
            active: false,
        },
        {
            name:"Reggae 141",
            artist: "Reggae141",
            cover: "https://img.freepik.com/vector-gratis/concepto-marco-neon-aire_52683-52393.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://hestia2.cdnstream.com/1301_32",
            active: false,
        },
        {
            name:"Radio play",
            artist: "Radio play",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://laradiossl.online:10315/stream/1/",
            active: false,
        },
        {
            name:"Funx Reggae",
            artist: "Funx Reggae",
            cover: "https://img.freepik.com/foto-gratis/fondo-musica-o-podcast-auriculares-taza-cafe-mesa-azul-plana-vista-superior-plana_501050-983.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://icecast.omroep.nl/funx-reggae-bb-mp3",
            active: false,
        },
        {
            name:"Listen Australia Reggae",
            artist: "ListenAustraliaReggae",
            cover: "https://img.freepik.com/vector-gratis/silueta-aparato-radio_23-2147501018.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://streamer.radio.co/s7089e2ea4/listen",
            active: false,
        },
        {
            name:"Reggae Mix",
            artist: "ReggaeMix",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://france1.coollabel-productions.com/proxy/reggaemix340/stream/1/",
            active: false,
        },
        {
            name:"Ambiance Reggae",
            artist: "AmbianceReggae",
            cover: "https://img.freepik.com/vector-gratis/aire-letrero-neon-marco_23-2148818543.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://streamingv2.shoutcast.com/Ambiance-Reggae",
            active: false,
        },
        {
            name:"Perfect Reggae",
            artist: "PerfectReggae",
            cover: "https://img.freepik.com/vector-gratis/fondo-musica_53876-90528.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://n0d.radiojar.com/ezs0qr9m4qruv?rj-ttl=5&rj-tok=AAABhDOqki0AhZWzmcNpH4ZQNA",
            active: false,
        },
        {
            name:"RMF Reggae",
            artist: "RMFReggae.",
            cover: "https://img.freepik.com/vector-gratis/dia-mundial-radio-diseno-plano_23-2148802732.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://rs102-krk.rmfstream.pl/REGGAE",
            active: false,
        },
        {
            name:"Tropique Reggae",
            artist: "TropiqueReggae",
            cover: "https://img.freepik.com/vector-gratis/marco-neon-vivo-aire_23-2148758076.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://listen.radioking.com/radio/261652/stream/306715",
            active: false,
        },
        {
            name:"Radio play",
            artist: "Radio play",
            cover: "https://img.freepik.com/vector-gratis/texto-plano-dia-mundial-radio_23-2148825802.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://laradiossl.online:10315/stream/1/",
            active: false,
        },
        {
            name:"Conexao Reggae",
            artist: "ConexaoReggae",
            cover: "ttps://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stm13.xcast.com.br:7016/stream/1/",
            active: false,
        },
        {
            name:"Eskifaia Reggae",
            artist: "EskifaiaReggae",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://srv.webradiomanager.fr:1625/stream",
            active: false,
        },
        {
            name:"LWR Radio reggae",
            artist: "LWRRadioreggae",
            cover: "https://img.freepik.com/vector-gratis/fondo-retro-dia-mundial-radio_23-2147594195.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://lwrreggae-zaklwr10.radioca.st/stream",
            active: false,
        },
    ];
}

export default chillHop;


